name: Archive Cursor Releases

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      force_update:
        description: '强制更新所有版本'
        required: false
        default: 'false'
      start_version:
        description: '起始版本(可选)'
        required: false
      end_version:
        description: '结束版本(可选)'
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Download Version Info
      run: |
        mkdir -p downloads
        curl -s https://res.1073studio.com/cursor_versions.txt | sort -n > cursor_versions.txt

    - name: Process Versions and Download Files
      run: |
        while IFS=, read -r date version buildid; do
          # 检查版本范围
          if [ ! -z "${{ github.event.inputs.start_version }}" ] && [ "$version" \< "${{ github.event.inputs.start_version }}" ]; then
            echo "Skipping version $version (before start version)"
            continue
          fi
          if [ ! -z "${{ github.event.inputs.end_version }}" ] && [ "$version" \> "${{ github.event.inputs.end_version }}" ]; then
            echo "Skipping version $version (after end version)"
            continue
          fi

          echo "Processing version $version (Build $buildid)"
          
          # Windows x64
          curl -L -o "downloads/Cursor Setup $version - Build $buildid-x64.exe" \
            "https://download.todesktop.com/230313mzl4w4u92/Cursor%20Setup%20$version%20-%20Build%20$buildid-x64.exe"
          
          # Windows ARM64
          curl -L -o "downloads/Cursor Setup $version - Build $buildid-arm64.exe" \
            "https://download.todesktop.com/230313mzl4w4u92/Cursor%20Setup%20$version%20-%20Build%20$buildid-arm64.exe"
          
          # Mac Universal
          curl -L -o "downloads/Cursor Mac Installer ($buildid).zip" \
            "https://download.todesktop.com/230313mzl4w4u92/Cursor%20Mac%20Installer%20($buildid).zip"
          
          # Mac ARM64 & x64
          curl -L -o "downloads/Cursor $version - Build $buildid-arm64.dmg" \
            "https://download.todesktop.com/230313mzl4w4u92/Cursor%20$version%20-%20Build%20$buildid-arm64.dmg"
          curl -L -o "downloads/Cursor $version - Build $buildid-x64.dmg" \
            "https://download.todesktop.com/230313mzl4w4u92/Cursor%20$version%20-%20Build%20$buildid-x64.dmg"
          
          # Linux
          curl -L -o "downloads/cursor-$version-build-$buildid-x86_64.AppImage" \
            "https://download.todesktop.com/230313mzl4w4u92/cursor-$version-build-$buildid-x86_64.AppImage"

          echo "TAG_NAME=Cursor $version" >> $GITHUB_ENV
          echo "RELEASE_DATE=$date" >> $GITHUB_ENV
          echo "BUILD_ID=$buildid" >> $GITHUB_ENV
          break  # 只处理最新版本
        done < cursor_versions.txt

    - name: Publish to GitHub Releases
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        name: "${{ env.TAG_NAME }} (${{ env.RELEASE_DATE }})"
        body: |
          Build ID: ${{ env.BUILD_ID }}
          Release Date: ${{ env.RELEASE_DATE }}
        files: |
          downloads/*

    - name: Send failure notification
      if: failure()
      run: |
        echo "Workflow Archive Cursor Releases failed."
