name: Archive Cursor Releases

on:
  workflow_dispatch:
    inputs:
      force_update:
        description: '强制更新所有版本'
        required: false
        default: 'false'
      start_version:
        description: '起始版本(可选)'
        required: false
      end_version:
        description: '结束版本(可选)'
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Process Cursor Releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash -x ./scripts/processCursorReleases.sh "${{ github.event.inputs.start_version }}" "${{ github.event.inputs.end_version }}" "${{ github.event.inputs.force_update }}"


